DROP TABLE IF EXISTS Price;  
CREATE TABLE Price (  
PRICE_LIST INT AUTO_INCREMENT PRIMARY KEY,
BRAND_ID INT NOT NULL,  
START_DATE DATETIME NOT NULL,  
END_DATE DATETIME NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY INT NOT NULL,
PRICE DECIMAL(9,2) NOT NULL,
CURR VARCHAR(10) NOT NULL
); 

DROP TABLE IF EXISTS Brand;  
CREATE TABLE Brand (  
BRAND_ID INT NOT NULL  PRIMARY KEY,  
BRAND_NAME VARCHAR(50) NOT NULL
);   

ALTER TABLE Price
    ADD FOREIGN KEY (BRAND_ID)
        REFERENCES Brand (BRAND_ID);